/**
 * Maps color variations and shades to standardized color options
 */
export const colorMappings: Record<string, string> = {
  // Basic colors
  'black': 'Black',
  'white': 'White',
  'grey': 'Grey',
  'gray': 'Grey',
  'silver': 'Silver',
  'brown': 'Brown',
  'tan': 'Beige',
  'beige': 'Beige',
  'cream': 'Cream',
  'ivory': 'Ivory',
  'nude': 'Nude',
  'navy': 'Navy',
  'blue': 'Blue',
  'red': 'Red',
  'burgundy': 'Burgundy',
  'maroon': 'Burgundy',
  'pink': 'Pink',
  'purple': 'Purple',
  'lilac': 'Lavender',
  'lavender': 'Lavender',
  'violet': 'Purple',
  'green': 'Green',
  'olive': 'Olive',
  'khaki': 'Khaki',
  'teal': 'Teal',
  'turquoise': 'Turquoise',
  'mint': 'Mint',
  'yellow': 'Yellow',
  'gold': 'Gold',
  'mustard': 'Mustard',
  'orange': 'Orange',
  'coral': 'Coral',
  'peach': 'Peach',
  'rust': 'Rust',
  
  // Shades and variations
  'light blue': 'Light Blue',
  'baby blue': 'Light Blue',
  'sky blue': 'Light Blue',
  'dark blue': 'Navy',
  'royal blue': 'Blue',
  'cobalt': 'Blue',
  'indigo': 'Navy',
  'light green': 'Mint',
  'sage': 'Sage',
  'emerald': 'Green',
  'forest green': 'Dark Green',
  'dark green': 'Dark Green',
  'light pink': 'Light Pink',
  'hot pink': 'Pink',
  'fuchsia': 'Pink',
  'magenta': 'Pink',
  'rose': 'Pink',
  'blush': 'Light Pink',
  'salmon': 'Coral',
  'light purple': 'Lavender',
  'dark purple': 'Purple',
  'plum': 'Purple',
  'mauve': 'Lavender',
  'light red': 'Coral',
  'crimson': 'Red',
  'scarlet': 'Red',
  'wine': 'Burgundy',
  'light yellow': 'Yellow',
  'lemon': 'Yellow',
  'dark yellow': 'Mustard',
  'light orange': 'Peach',
  'tangerine': 'Orange',
  'camel': 'Camel',
  'taupe': 'Taupe',
  'chestnut': 'Brown',
  'chocolate': 'Brown',
  'coffee': 'Brown',
  'espresso': 'Brown',
  'copper': 'Rust',
  
  // Neutrals
  'charcoal': 'Grey',
  'ash': 'Grey',
  'off-white': 'Cream',
  'eggshell': 'Ivory',
  'platinum': 'Silver',
  
  // Patterns
  'checkered': 'Patterned',
  'striped': 'Patterned',
  'dotted': 'Patterned',
  'leopard': 'Patterned',
  'animal': 'Patterned',
  'print': 'Patterned',
  'polka': 'Patterned',
  'flower': 'Floral',
  'floral': 'Floral',
  'botanical': 'Floral',
  'rainbow': 'Multicolor',
  'colorful': 'Multicolor',
  'multi': 'Multicolor'
};

/**
 * Gets standard color options for dropdowns
 */
export function getColorOptions(): string[] {
  return [
    'Black',
    'White',
    'Grey',
    'Silver',
    'Brown',
    'Beige',
    'Cream',
    'Ivory',
    'Nude',
    'Navy',
    'Blue',
    'Light Blue',
    'Red',
    'Burgundy',
    'Pink',
    'Light Pink',
    'Purple',
    'Lavender',
    'Green',
    'Dark Green',
    'Mint',
    'Sage',
    'Olive',
    'Khaki',
    'Teal',
    'Turquoise',
    'Yellow',
    'Gold',
    'Mustard',
    'Orange',
    'Coral',
    'Peach',
    'Rust',
    'Camel',
    'Taupe',
    'Multicolor',
    'Floral',
    'Patterned'
  ];
}
